export const SEARCH_FOCUS = "header/search_focus"
export const SEARCH_BLUR = "header/search_blur"
export const MOUSE_ENTER = "header/mouse_enter"
export const MOUSE_LEAVE = "header/mouse_leave"
export const CHANGE_SEARCH_ITEMS = "header/changeSearchItems"
export const CHANGE_SEARCH_ITEMS_PAGE = "header/changeSearchItemsPage"